version: 2
jobs:
 build:
   docker:
     — image: circleci/ruby:3.0.0-node-browsers
       environment:
         RAILS_ENV: test
     — image: circleci/postgres:10.3
       environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: “teamkongmdfk00”
     steps:
       — checkout
       # Database setup
       — run:
         name: Create Database
         command: bundle exec rake db:create
       — run:
         name: Load Database Schema
         command: bundle exec rake db:schema:load
       # run tests!
       — run:
         name: Run RSpec Tests
         command: |
           TESTFILES=$(circleci tests glob “spec/**/*_spec.rb” |    circleci tests split)
         bundle exec rspec — ${TESTFILES}