version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: yarn install
          command: yarn install --check-files
      - run:
          name: create-migrate db
          command: bundle exec rails db:create db:migrate
      - run:
            name: test
            command: bundle exec rspec

        
