version: 2.1

jobs:
    build:
      docker:
         - image: circleci/ruby:3.0.0-node
         - image: circleci/postgres
           environment:
             POSTGRES_USER: root
             POSTGRES_PASSWORD: teamkongmdfk00
      steps:
       - checkout
       - run:
           name: bundle install
           command: bundle install
       - run:
           name: yarn install
           command: yarn install --check-files
       - run:
           name: db create
           command: bundle exec rake db:create
       - run: 
           name: db load migrate
           command: bundle exec rake db:migrate
       #- run: bundle exec rspec spec/controllers/checks_controller_spec.rb
    test:
      docker:
         - image: circleci/ruby:3.0.0-node
      steps:
        - checkout
        - run: bundle exec rspec spec/controllers/checks_controller_spec.rb
workflows:
  build_test:
    jobs:
      - build
      - test: 
         requires:
           - build